# name: learn-github-actions
# on: [push]
# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
# #       - uses: actions/setup-node@v1
# #       - run: npm install -g bats
# #       - run: bats -v
# #       - run: pwd
#       - run: docker build . -t softgalaxy/simpleweb_test
#       #- run: ping -c 4 8.8.8.8

# This is a basic workflow to help you get started with Actions

name: CI to Dockerhub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:        
          version: latest

      - name: Prepare      
        if: success()      
        id: prepare      
        run: |        
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewebpi4b:latest

        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

    services:
      db:
        image: cescorpredteam/app:db-redteam
        volumes:
          - postgres_data:/var/lib/postgresql/data/
#         env:
#           - POSTGRES_USER=cesuser
#           - POSTGRES_PASSWORD=/ZyoyCg?,y0n
#           - POSTGRES_DB=liddatabase
#         restart: always
     


